service: weight-domain

frameworkVersion: '3'

plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-2
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
