service: weight-domain

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-2
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
