name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: make _deps

      - name: Determine changed folders
        id: changes
        run: |
          echo "CHANGED_FOLDERS=$(git diff --name-only origin/main...HEAD | grep '^libs/' | cut -d/ -f2 | sort -u)" >> $GITHUB_ENV
